### PR TITLE
release 2021.2

### PR DESCRIPTION
**Pull request by matthiasdiener**

### CODE REVIEW

**Comment by inducer** [comment]
Could you explain the context? I'm a bit surprised given that there's tons of work in flight at the moment.

**Comment by matthiasdiener** [comment]
> Could you explain the context? I'm a bit surprised given that there's tons of work in flight at the moment.

I thought this might make a good "checkpoint" for development - there have been a few major changes compared to the last release, e.g.:
- namespace removal
- many more operations
- kernel callables

Looking at the open PRs, there doesn't seem to be a lot of critical work open at the moment (imho).

**Comment by inducer** [comment]
Hmm, you're right. There's not a lot pending for pytato, I must've been confused between all the different things going on. Fair, let's do it.

**Comment by inducer** [comment]
https://pypi.org/project/pytato/2021.2/

**Pull request merged**
