### PR TITLE
Fix Downstream MIRGE-Com CI (?)

### PR DESCRIPTION
**Pull request by kaushikcfd**
See: https://github.com/illinois-ceesd/mirgecom/pull/316

### CODE REVIEW

**Comment by kaushikcfd** [comment]
Hmm.. the same link error exists here too. Looks like the linker cannot find `libc`'s shared objects.

**Comment by matthiasdiener** [comment]
We'll need to apply the same workaround as here (using OpenMPI should be fine): https://github.com/illinois-ceesd/mirgecom/pull/525/files#diff-464a640b719a59f4671d01f644ed750894b34669d94035fbe89038c3d7018510R25

**Comment by matthiasdiener** [comment]
> We'll need to apply the same workaround as here (using OpenMPI should be fine): https://github.com/illinois-ceesd/mirgecom/pull/525/files#diff-464a640b719a59f4671d01f644ed750894b34669d94035fbe89038c3d7018510R25

This should probably be done in ci-support-v0

**Comment by kaushikcfd** [comment]
@matthiasdiener: Thanks for taking a look here! I see, will open a PR over there then.

**Pull request closed without merging**
