### PR TITLE
Handle `Named` tags

### PR DESCRIPTION
**Pull request by kaushikcfd**

### CODE REVIEW

**Comment by inducer** [comment]
I guess I'll need to roll a pytools release in order for this to pass? Let me do that.

**Comment by kaushikcfd** [comment]
Aah sorry. This is weird, I thought we have [pytools as a requirement](https://github.com/inducer/pytato/blob/main/requirements.txt#L1)  so we should have been good.

**Comment by inducer** [comment]
https://pypi.org/project/pytools/2021.2.9/#history

**Comment by inducer** [comment]
(We'll still have to wait until it makes its way into conda forge. It's a pyopencl dep, that's why it's special.)

**Review by inducer — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
