### PR TITLE
Eliminate recursive forwarding in mappers

### PR DESCRIPTION
**Pull request by majosm**
@inducer Turns out I didn't revert these changes after all, I just wasn't looking far enough down the commit list. 🙂

(I'll submit the `InlinedExpressionGenMapper` changes as a separate PR since they're a little less trivial.)

### CODE REVIEW

**Comment by inducer** [comment]
Oh. The failures are my problem. I saw that mirgecom had switched to Mambaforge for installs, and I figured I'd be a copycat. https://github.com/inducer/ci-support/commit/4b868fe4ed49f26bb108c856d94143ab86710f2e Apparently I broke it.

**Comment by inducer** [comment]
Fixed! Though this matches my recollection--these methods are mainly for mypy's benefit. Maybe you could make them `if TYPE_CHECKING`?

**Review by inducer — APPROVED** [review]

**Comment by inducer** [comment]
Thanks!

**Comment by inducer** [comment]
(I'll wait until you un-draft this.)

**Comment by majosm** [comment]
> (I'll wait until you un-draft this.)

Done!

**Pull request merged**
