### PR TITLE
Disable bounds checking when no loopy call present

### PR DESCRIPTION
**Pull request by matthiasdiener**
Alternative to https://github.com/inducer/arraycontext/pull/239.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
Is this what you had in mind @inducer?

**Comment by inducer** [comment]
Yep, that's spot on. I think this makes sense. I'll wait for you to un-draft.

**Comment by kaushikcfd** [comment]
Why are we disabling the bounds check only when there's a loopy call. Shouldn't we always disable it?

**Comment by kaushikcfd** [comment]
> 
Why are we disabling the bounds check only when there's a loopy call. Shouldn't we always disable it?

Aah I think I see it. loopy_call corresponds to user code which needs bounds checking. Sorry for the noise.

**Comment by matthiasdiener** [comment]
> Yep, that's spot on. I think this makes sense. I'll wait for you to un-draft.

Thanks! I've set it to ready for review.

**Comment by inducer** [comment]
Given @kaushikcfd's question, I think it'd make sense to include a comment to explain the reasoning.

**Comment by matthiasdiener** [comment]
> Given @kaushikcfd's question, I think it'd make sense to include a comment to explain the reasoning.

What do you think of ab38959?

**Comment by inducer** [comment]
Works for me. Thanks!

**Pull request merged**
