### PR TITLE
Turn off implicit numpy-array handling in generated loopy

### PR DESCRIPTION
**Pull request by inducer**
For a moderate cost savings in the wrapper.

### CODE REVIEW

**Review by kaushikcfd — COMMENTED** [review]
I actually like `no_numpy=False` for testing/debugging as a default.

**Comment by kaushikcfd** [comment]
Another thing being: I'm scared the amount of tests this will break. :)

**Comment by inducer** [comment]
> I actually like `no_numpy=False` for testing/debugging as a default.

I'm torn. At best, it should be a user-option. (but then likely in the array context, which should set it to `False`)

> Another thing being: I'm scared the amount of tests this will break. :)

We'll find out together.

**Comment by kaushikcfd** [comment]
> At best, it should be a user-option. (but then likely in the array context, which should set it to False)

I agree that we should set this option in `arraycontext`. `pt.generate_loopy` already takes in `options` argument. (cf [here](https://documen.tician.de/pytato/codegen.html?highlight=generate_loopy#pytato.generate_loopy))

**Comment by inducer** [comment]
Superseded by https://github.com/inducer/arraycontext/pull/72 and https://github.com/inducer/pytato/pull/135.

**Pull request closed without merging**
