### PR TITLE
Add (failing) `test_random_dag_against_numpy_additional_gen`

### PR DESCRIPTION
**Pull request by inducer**
This emerged from debugging CI failures in #148. For "Step 6", it makes an absolutely massive DAG on my machine and then fails with the following:
```
Step 1 141
Step 2 142
Step 3 143
Step 4 144
Step 5 145
Step 6 146
Traceback (most recent call last):
  File "/home/andreas/src/pytato/test/test_codegen.py", line 1570, in <module>
    exec(sys.argv[1])
  File "<string>", line 1, in <module>
  File "/home/andreas/src/pytato/test/test_codegen.py", line 1399, in test_random_dag_against_numpy_additional_gen
    np.testing.assert_allclose(res_no_comm, res_no_comm_numpy)
  File "/home/andreas/src/env-3.10/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/home/andreas/src/env-3.10/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)AssertionError: Not equal to tolerance rtol=1e-07, atol=0
Mismatched elements: 6 / 16 (37.5%)
Max absolute difference: 1.15027753
Max relative difference: 19.87696907
x: array([[ 1.57218 , -0.073723,  0.22487 ,  0.401481],
       [ 1.092408, -0.553496, -0.254231,  0.042465],
       [ 0.189805, -0.288266, -0.003712,  0.183803],
       [ 1.705357,  0.073492,  0.441674,  1.773128]])
 y: array([[ 0.421903, -0.073723,  0.22487 ,  0.401481],
       [-0.05787 , -0.553496, -0.254231,  0.042465],
       [ 0.189805, -0.302304, -0.003712,  0.183803],
       [ 0.55508 ,  0.059454,  0.441674,  1.637791]])
```

This happens with both pocl and Intel CL, so I think this might be a legitimate code generation bug.

:warning: Do not click "rebase" on this PR without a good reason, it may wreck the failing example (which we do need to understand).

cc @kaushikcfd @matthiasdiener

### CODE REVIEW

**Comment by kaushikcfd** [comment]
Data: Transforming with `pt.materialize_with_mpms` doesn't error. Reproduced the exact reported error without it on `"pocl:pthread"`.

**Comment by kaushikcfd** [comment]
Some more data:
1. with `-cl-opt-disable` also results in wrong output. (Does that mean wrong loopy/pytato codegen?)
2. Here's the kernel: https://gist.github.com/kaushikcfd/ec464dae8f6d7d9ce55c8528376a87aa

**Comment by inducer** [comment]
> (Does that mean wrong loopy/pytato codegen?)

I'm almost sure that that's the case. It fails with both pocl and Intel CL, so if it was the C compiler, then both of them would have to miscompile that code.

**Comment by kaushikcfd** [comment]
More data:
1. Also fails for i=49 (much smaller DAG), with
```
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

x and y nan location mismatch:
 x: array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])
 y: array([[4.087341, 3.724727, 3.674119, 4.043893],
       [4.087341, 3.952326, 3.678215, 4.043893],
       [4.087341, 3.724727, 3.941615, 4.043893],
       [4.087341, 3.724727, 3.674119, 4.043893]]
```

**Comment by kaushikcfd** [comment]
Here's a simpler that fails:
```python
import numpy as np
import pytato as pt
import pyopencl as cl


ctx = cl.create_some_context()
cq = cl.CommandQueue(ctx)


def kernel(usr_np, *,
           _pt_data, _pt_data_13, _pt_data_1, _pt_data_4, _pt_data_9,
           _pt_data_7, _pt_data_8, _pt_data_14):
    _pt_tmp_17 = _pt_data_1 @ _pt_data_4
    _pt_tmp_16 = usr_np.reshape(_pt_tmp_17, (4, 1, 4))
    _pt_tmp_53 = _pt_data_8 @ _pt_data_9
    _pt_tmp_42 = usr_np.maximum(_pt_data_7, _pt_tmp_53)
    _pt_tmp_30 = usr_np.reshape(_pt_tmp_42, (1, 4, 4))
    _pt_tmp_28 = usr_np.abs(_pt_tmp_30) ** _pt_data_14
    _pt_tmp_27 = usr_np.sum(_pt_tmp_28, axis=2)
    _pt_tmp_15 = _pt_tmp_16 / _pt_tmp_27
    _pt_tmp_14 = _pt_tmp_15[0]
    _pt_tmp_4 = usr_np.abs(_pt_data) ** _pt_tmp_14
    _pt_tmp_71 = usr_np.reshape(_pt_data_13, (4, 1, 4))
    _pt_tmp_0 = usr_np.maximum(_pt_tmp_4, _pt_tmp_71)
    return _pt_tmp_0


def get_np_input_args():
    return {
        "_pt_data_13": np.random.rand(4, 4),
        "_pt_data_1": np.random.rand(4, 4),
        "_pt_data_9": np.random.rand(4, 4),
        "_pt_data_4": np.random.rand(4, 4),
        "_pt_data_7": np.random.rand(4),
        "_pt_data": np.random.rand(4, 4),
        "_pt_data_8": np.random.rand(4, 4),
        "_pt_data_14": np.random.rand(4, 4, 1),
    }


np_inputs = get_np_input_args()
np_result = kernel(np, **np_inputs)
pt_dag = kernel(pt, **{kw: pt.make_data_wrapper(arg)
                       for kw, arg in np_inputs.items()})
_, (pt_result,) = pt.generate_loopy(pt_dag)(cq)
np.testing.assert_allclose(pt_result, np_result)
```

**Comment by inducer** [comment]
Nice! That looks a lot more manageable than the original.

**Comment by matthiasdiener** [comment]
Replacing `np.random.rand` with `np.zeros` in the code above makes this fail reproducibly.

**Comment by matthiasdiener** [comment]
An even simpler reproducer: 

```python
import numpy as np
import pytato as pt
import pyopencl as cl
import loopy as lp


ctx = cl.create_some_context()
cq = cl.CommandQueue(ctx)


def kernel(usr_np, _pt_data_9):
    _pt_tmp_53 = _pt_data_9 @ _pt_data_9
    _pt_tmp_42 = usr_np.maximum(_pt_tmp_53, _pt_tmp_53)
    _pt_tmp_27 = usr_np.sum(_pt_tmp_42)
    _pt_tmp_0 = usr_np.maximum(_pt_tmp_27, _pt_tmp_53)
    return _pt_tmp_0


def get_np_input_args():
    return {
        "_pt_data_9": np.ones((2, 2)),
    }


np_inputs = get_np_input_args()
np_result = kernel(np, **np_inputs)
pt_dag = kernel(pt, **{kw: pt.make_data_wrapper(arg)
                       for kw, arg in np_inputs.items()})

knl = pt.generate_loopy(pt_dag, options=lp.Options(write_cl=True))

_, (pt_result,) = knl(cq)

from pytato import show_dot_graph
print(get_num_nodes(pt_dag))

np.testing.assert_allclose(pt_result, np_result)
```

**Comment by kaushikcfd** [comment]
This happens because of wrong code generation by loopy. See here: https://github.com/inducer/loopy/issues/533.

**Comment by inducer** [comment]
Took @matthiasdiener's reproducer from https://github.com/inducer/pytato/pull/255#issuecomment-1028248714 and turned it into a regression test: https://github.com/inducer/pytato/pull/260.

**Pull request closed without merging**
