### PR TITLE
Do not allow passing bound arguments to BoundProgram

### LINKED ISSUE #28: Should "overriding" bound arguments be allowed?
On `master` the the data of "x" is overridden. Was this intentional?

```python
ns = pt.Namespace()
x_in = np.ones(10)
x = pt.make_data_wrapper(ns, x_in, name="x")
prg = pt.generate_loopy(42*x, pt.PyOpenCLTarget(queue))
evt, (out1,) = prg()
evt, (out2,) = prg(x=np.random.rand(10))
```

### PR DESCRIPTION
**Pull request by kaushikcfd**
Fixes #28

### CODE REVIEW

**Comment by inducer** [comment]
Hmmm... button looked green, but CI didn't run? Weird.

**Comment by inducer** [comment]
At any rate, thanks for getting this fixed quickly.

**Comment by kaushikcfd** [comment]
Yep, the CI status on master is not shown.

**Comment by kaushikcfd** [comment]
Passed on gitlab: https://gitlab.tiker.net/inducer/pytato/-/pipelines/124351, so not too problematic.

**Comment by inducer** [comment]
Phew! :)

**Pull request merged**
