### PR TITLE
Canonicalize DAG

### PR DESCRIPTION
**Pull request by kaushikcfd**
Implements the discussion from #44

### CODE REVIEW

**Comment by inducer** [comment]
Unsubscribing for now due to failing CI. Ping me when it's ready.

**Comment by inducer** [comment]
@kaushikcfd This is made obsolete by the removal of namespaces, right?

**Comment by kaushikcfd** [comment]
Yep, this isn't needed anymore. Let's bid this PR adieu.

**Comment by inducer** [comment]
:wave:  :)

**Pull request closed without merging**
