### PR TITLE
Revert "Implement numpy 2 type promotion"

### PR DESCRIPTION
**Pull request by matthiasdiener**
This reverts commit f0deaea1130fe0dd4dfa52bee540910305de9c70.

cc #510.

### CODE REVIEW

**Comment by inducer** [comment]
I'd say it is supremely unlikely that this will get merged. Pytato implements numpy semantics, numpy changed what these semantics are, and so our hands are tied. Numpy is the boss.

**Comment by kaushikcfd** [comment]
I agree, we must comply with Numpy. Any particular reason why this is needed?

**Comment by matthiasdiener** [comment]
Sorry for the confusion, at the moment this PR is only to debug slowdowns we have seen in production.

**Comment by matthiasdiener** [comment]
Closing in favor #540 (+ some investigation in #542).

**Pull request closed without merging**
